# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/cpp-workspace/quant_fin_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/cpp-workspace/quant_fin_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cpp-workspace/quant_fin_lib/CMakeFiles /root/cpp-workspace/quant_fin_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cpp-workspace/quant_fin_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quant_fin_lib

# Build rule for target.
quant_fin_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quant_fin_lib
.PHONY : quant_fin_lib

# fast build rule for target.
quant_fin_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/build
.PHONY : quant_fin_lib/fast

#=============================================================================
# Target rules for targets named quant_fin_main

# Build rule for target.
quant_fin_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quant_fin_main
.PHONY : quant_fin_main

# fast build rule for target.
quant_fin_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_main.dir/build.make CMakeFiles/quant_fin_main.dir/build
.PHONY : quant_fin_main/fast

#=============================================================================
# Target rules for targets named run_quant_fin_main

# Build rule for target.
run_quant_fin_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_quant_fin_main
.PHONY : run_quant_fin_main

# fast build rule for target.
run_quant_fin_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_quant_fin_main.dir/build.make CMakeFiles/run_quant_fin_main.dir/build
.PHONY : run_quant_fin_main/fast

#=============================================================================
# Target rules for targets named test_quant_fin_lib

# Build rule for target.
test_quant_fin_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_quant_fin_lib
.PHONY : test_quant_fin_lib

# fast build rule for target.
test_quant_fin_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_quant_fin_lib.dir/build.make CMakeFiles/test_quant_fin_lib.dir/build
.PHONY : test_quant_fin_lib/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_main.dir/build.make CMakeFiles/quant_fin_main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_main.dir/build.make CMakeFiles/quant_fin_main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_main.dir/build.make CMakeFiles/quant_fin_main.dir/main.cpp.s
.PHONY : main.cpp.s

src/pricing/binomial_tree.o: src/pricing/binomial_tree.cpp.o
.PHONY : src/pricing/binomial_tree.o

# target to build an object file
src/pricing/binomial_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/binomial_tree.cpp.o
.PHONY : src/pricing/binomial_tree.cpp.o

src/pricing/binomial_tree.i: src/pricing/binomial_tree.cpp.i
.PHONY : src/pricing/binomial_tree.i

# target to preprocess a source file
src/pricing/binomial_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/binomial_tree.cpp.i
.PHONY : src/pricing/binomial_tree.cpp.i

src/pricing/binomial_tree.s: src/pricing/binomial_tree.cpp.s
.PHONY : src/pricing/binomial_tree.s

# target to generate assembly for a file
src/pricing/binomial_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/binomial_tree.cpp.s
.PHONY : src/pricing/binomial_tree.cpp.s

src/pricing/black_scholes.o: src/pricing/black_scholes.cpp.o
.PHONY : src/pricing/black_scholes.o

# target to build an object file
src/pricing/black_scholes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/black_scholes.cpp.o
.PHONY : src/pricing/black_scholes.cpp.o

src/pricing/black_scholes.i: src/pricing/black_scholes.cpp.i
.PHONY : src/pricing/black_scholes.i

# target to preprocess a source file
src/pricing/black_scholes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/black_scholes.cpp.i
.PHONY : src/pricing/black_scholes.cpp.i

src/pricing/black_scholes.s: src/pricing/black_scholes.cpp.s
.PHONY : src/pricing/black_scholes.s

# target to generate assembly for a file
src/pricing/black_scholes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/black_scholes.cpp.s
.PHONY : src/pricing/black_scholes.cpp.s

src/pricing/monte_carlo.o: src/pricing/monte_carlo.cpp.o
.PHONY : src/pricing/monte_carlo.o

# target to build an object file
src/pricing/monte_carlo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/monte_carlo.cpp.o
.PHONY : src/pricing/monte_carlo.cpp.o

src/pricing/monte_carlo.i: src/pricing/monte_carlo.cpp.i
.PHONY : src/pricing/monte_carlo.i

# target to preprocess a source file
src/pricing/monte_carlo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/monte_carlo.cpp.i
.PHONY : src/pricing/monte_carlo.cpp.i

src/pricing/monte_carlo.s: src/pricing/monte_carlo.cpp.s
.PHONY : src/pricing/monte_carlo.s

# target to generate assembly for a file
src/pricing/monte_carlo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/pricing/monte_carlo.cpp.s
.PHONY : src/pricing/monte_carlo.cpp.s

src/quant_fin_lib.o: src/quant_fin_lib.cpp.o
.PHONY : src/quant_fin_lib.o

# target to build an object file
src/quant_fin_lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/quant_fin_lib.cpp.o
.PHONY : src/quant_fin_lib.cpp.o

src/quant_fin_lib.i: src/quant_fin_lib.cpp.i
.PHONY : src/quant_fin_lib.i

# target to preprocess a source file
src/quant_fin_lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/quant_fin_lib.cpp.i
.PHONY : src/quant_fin_lib.cpp.i

src/quant_fin_lib.s: src/quant_fin_lib.cpp.s
.PHONY : src/quant_fin_lib.s

# target to generate assembly for a file
src/quant_fin_lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/quant_fin_lib.cpp.s
.PHONY : src/quant_fin_lib.cpp.s

src/risk/greeks.o: src/risk/greeks.cpp.o
.PHONY : src/risk/greeks.o

# target to build an object file
src/risk/greeks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/greeks.cpp.o
.PHONY : src/risk/greeks.cpp.o

src/risk/greeks.i: src/risk/greeks.cpp.i
.PHONY : src/risk/greeks.i

# target to preprocess a source file
src/risk/greeks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/greeks.cpp.i
.PHONY : src/risk/greeks.cpp.i

src/risk/greeks.s: src/risk/greeks.cpp.s
.PHONY : src/risk/greeks.s

# target to generate assembly for a file
src/risk/greeks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/greeks.cpp.s
.PHONY : src/risk/greeks.cpp.s

src/risk/var.o: src/risk/var.cpp.o
.PHONY : src/risk/var.o

# target to build an object file
src/risk/var.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/var.cpp.o
.PHONY : src/risk/var.cpp.o

src/risk/var.i: src/risk/var.cpp.i
.PHONY : src/risk/var.i

# target to preprocess a source file
src/risk/var.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/var.cpp.i
.PHONY : src/risk/var.cpp.i

src/risk/var.s: src/risk/var.cpp.s
.PHONY : src/risk/var.s

# target to generate assembly for a file
src/risk/var.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/risk/var.cpp.s
.PHONY : src/risk/var.cpp.s

src/utils/allocators.o: src/utils/allocators.cpp.o
.PHONY : src/utils/allocators.o

# target to build an object file
src/utils/allocators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/utils/allocators.cpp.o
.PHONY : src/utils/allocators.cpp.o

src/utils/allocators.i: src/utils/allocators.cpp.i
.PHONY : src/utils/allocators.i

# target to preprocess a source file
src/utils/allocators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/utils/allocators.cpp.i
.PHONY : src/utils/allocators.cpp.i

src/utils/allocators.s: src/utils/allocators.cpp.s
.PHONY : src/utils/allocators.s

# target to generate assembly for a file
src/utils/allocators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/utils/allocators.cpp.s
.PHONY : src/utils/allocators.cpp.s

src/yield_curve/interpolation.o: src/yield_curve/interpolation.cpp.o
.PHONY : src/yield_curve/interpolation.o

# target to build an object file
src/yield_curve/interpolation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/yield_curve/interpolation.cpp.o
.PHONY : src/yield_curve/interpolation.cpp.o

src/yield_curve/interpolation.i: src/yield_curve/interpolation.cpp.i
.PHONY : src/yield_curve/interpolation.i

# target to preprocess a source file
src/yield_curve/interpolation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/yield_curve/interpolation.cpp.i
.PHONY : src/yield_curve/interpolation.cpp.i

src/yield_curve/interpolation.s: src/yield_curve/interpolation.cpp.s
.PHONY : src/yield_curve/interpolation.s

# target to generate assembly for a file
src/yield_curve/interpolation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quant_fin_lib.dir/build.make CMakeFiles/quant_fin_lib.dir/src/yield_curve/interpolation.cpp.s
.PHONY : src/yield_curve/interpolation.cpp.s

test/test_quant_fin_lib.o: test/test_quant_fin_lib.cpp.o
.PHONY : test/test_quant_fin_lib.o

# target to build an object file
test/test_quant_fin_lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_quant_fin_lib.dir/build.make CMakeFiles/test_quant_fin_lib.dir/test/test_quant_fin_lib.cpp.o
.PHONY : test/test_quant_fin_lib.cpp.o

test/test_quant_fin_lib.i: test/test_quant_fin_lib.cpp.i
.PHONY : test/test_quant_fin_lib.i

# target to preprocess a source file
test/test_quant_fin_lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_quant_fin_lib.dir/build.make CMakeFiles/test_quant_fin_lib.dir/test/test_quant_fin_lib.cpp.i
.PHONY : test/test_quant_fin_lib.cpp.i

test/test_quant_fin_lib.s: test/test_quant_fin_lib.cpp.s
.PHONY : test/test_quant_fin_lib.s

# target to generate assembly for a file
test/test_quant_fin_lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_quant_fin_lib.dir/build.make CMakeFiles/test_quant_fin_lib.dir/test/test_quant_fin_lib.cpp.s
.PHONY : test/test_quant_fin_lib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... run_quant_fin_main"
	@echo "... quant_fin_lib"
	@echo "... quant_fin_main"
	@echo "... test_quant_fin_lib"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/pricing/binomial_tree.o"
	@echo "... src/pricing/binomial_tree.i"
	@echo "... src/pricing/binomial_tree.s"
	@echo "... src/pricing/black_scholes.o"
	@echo "... src/pricing/black_scholes.i"
	@echo "... src/pricing/black_scholes.s"
	@echo "... src/pricing/monte_carlo.o"
	@echo "... src/pricing/monte_carlo.i"
	@echo "... src/pricing/monte_carlo.s"
	@echo "... src/quant_fin_lib.o"
	@echo "... src/quant_fin_lib.i"
	@echo "... src/quant_fin_lib.s"
	@echo "... src/risk/greeks.o"
	@echo "... src/risk/greeks.i"
	@echo "... src/risk/greeks.s"
	@echo "... src/risk/var.o"
	@echo "... src/risk/var.i"
	@echo "... src/risk/var.s"
	@echo "... src/utils/allocators.o"
	@echo "... src/utils/allocators.i"
	@echo "... src/utils/allocators.s"
	@echo "... src/yield_curve/interpolation.o"
	@echo "... src/yield_curve/interpolation.i"
	@echo "... src/yield_curve/interpolation.s"
	@echo "... test/test_quant_fin_lib.o"
	@echo "... test/test_quant_fin_lib.i"
	@echo "... test/test_quant_fin_lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

