name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          python3-dev \
          libgtest-dev \
          ninja-build \
          pkg-config \
          git \
          libspdlog-dev \
          libjsoncpp-dev \
          uuid-dev \
          openssl \
          libssl-dev \
          zlib1g-dev \
          libc-ares-dev \
          libcurl4-openssl-dev \
          libboost-all-dev

    - name: Build and Install GTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        cd ${GITHUB_WORKSPACE}

    - name: Install Drogon
      run: |
        git clone https://github.com/drogonframework/drogon
        cd drogon
        git checkout v1.8.7
        git submodule update --init
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ${GITHUB_WORKSPACE}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Build C++ Library and API
      run: |
        mkdir -p build/bin build/lib
        cmake -B build -G Ninja
        cmake --build build

    - name: Run C++ Tests
      run: |
        cd build/bin
        ./test_quant_fin_lib
        cd ../..

    - name: Install Python Dependencies
      run: poetry install

    - name: Run Python Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        poetry run pytest python_bindings/tests/
